DROP TABLE MENU_FOOD;
DROP TABLE MENU;
DROP TABLE RESTAURANT;
DROP TABLE ADDRESS;
DROP TABLE FOOD;
CREATE TABLE IF NOT exists FOOD(
ID INT(10) NOT NULL AUTO_INCREMENT,
CALORIES INT(10) NULL,
ISVEGAN BIT(1) NOT NULL,
NAME VARCHAR(255) NOT NULL,
PRICE INT(10) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE IF NOT exists ADDRESS(
ID INT(10) NOT NULL AUTO_INCREMENT,
CITY VARCHAR(255) NOT NULL,
COUNTRY VARCHAR(255) NOT NULL,
STREET VARCHAR(255) NOT NULL,
ZIPCODE VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE IF NOT exists RESTAURANT(
ID INT(10) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255) NOT NULL,
ADDRESS_ID INT(10) NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ID)
);

CREATE table IF NOT exists MENU(
ID int(10) NOT NULL AUTO_INCREMENT,
RESTAURANT_ID INT(10) NOT NULL,
FROMDATE DATE null,
TODATE DATE null,
primary key(ID),
foreign key(RESTAURANT_ID) references RESTAURANT(ID)
);

CREATE TABLE IF NOT exists MENU_FOOD(
MENU_ID INT(10) not null,
FOODS_ID INT(10) not null,
PRIMARY KEY(MENU_ID, FOODS_ID),
FOREIGN KEY(MENU_ID) REFERENCES MENU(ID),
FOREIGN KEY(FOODS_ID) REFERENCES FOOD(ID)

);